---

- name: Remove bootstrap host from {{ sat_hostgroup }} hostgroup
  delegate_to: localhost
  theforeman.foreman.host:
    name: "{{ item.name }}.{{ sat_domain }}"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent
  with_items:
    - '{{ openshift_bootstrap }}'
  when: openshift_bootstrap is defined and openshift_bootstrap | length > 0
  tags:
    - remove_hosts

- name: Remove master hosts from {{ sat_hostgroup }} hostgroup
  delegate_to: localhost
  theforeman.foreman.host:
    name: "{{ item.name }}.{{ sat_domain }}"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent
  with_items:
    - '{{ openshift_masters }}'
  when: openshift_masters is defined and openshift_masters | length > 0
  tags:
    - remove_hosts

- name: Remove worker hosts from {{ sat_hostgroup }} hostgroup
  delegate_to: localhost
  theforeman.foreman.host:
    name: "{{ item.name }}.{{ sat_domain }}"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent
  with_items:
    - '{{ openshift_workers }}'
  when: openshift_workers is defined and openshift_workers | length > 0
  tags:
    - remove_hosts

- name: Remove {{ sat_hostgroup }} hostgroup
  delegate_to: localhost
  theforeman.foreman.hostgroup:
    name: "{{ sat_hostgroup }}"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent

- name: Remove {{ sat_os }} OS
  delegate_to: localhost
  theforeman.foreman.operatingsystem:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: '{{ sat_os }}'
    major: "{{ sat_os_maj | int }}"
    state: absent

- name: Remove {{ sat_medium }} Medium
  delegate_to: localhost
  theforeman.foreman.installation_medium:
    name: "{{ sat_medium }}"
    locations:
      - "{{ sat_loc }}"
    organizations:
      - "{{ sat_org }}"
    os_family: "Coreos"
    path: "http://localhost/pub/rhcos"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent

- name: Remove Red Hat CoreOS PXELinux template
  delegate_to: localhost
  theforeman.foreman.provisioning_template:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: 'Red Hat CoreOS PXELinux'
    state: absent

- name: Cleanup Red Hat CoreOS boot files
  become: true
  file:
    path: '/var/www/html/pub/rhcos'
    state: absent
  when: ( coreos_unstage | bool )
