---
# defaults file for satellite_rhcos_pxe

ocp_version: "4.5.8"
rhcos_version: "4.5.6"
ocp_cluster_name: "caas"
ocp_base_domain: "example.com"

# OpenShift Hosts
openshift_bootstrap: {}
openshift_masters: {}
openshift_workers: {}

# Satellite settings

sat_server: 'https://localhost'
sat_ssl_enabled: false
sat_username: 'admin'
sat_password: 'password'

sat_org: "Disconnected Organization"
sat_loc: "Disconnected Zone"
sat_compute_resource: "baremetal"
sat_compute_profile: "2-Medium"
sat_domain: "example.com"
sat_subnet: "Private"
sat_svrname: "bootstrap"
sat_hostgroup: 'Coreos dev'
sat_medium: 'Red Hat CoreOS'
sat_os: 'RHCOS'
sat_os_maj: 8

# Coreos settings 

base_url: 'https://mirror.openshift.com/pub/openshift-v4'
arch: 'x86_64'
maj_ver: '{{ (rhcos_version | splitext)[0] }}'
coreos_ignition_url: ""
coreos_install_dev: "vda"
coreos_installer_kernel: "{{ base_url }}/{{ arch }}/dependencies/rhcos/{{ maj_ver }}/{{ rhcos_version }}/rhcos-{{ rhcos_version }}-{{ arch }}-installer-kernel-{{ arch }}"
coreos_installer_initrd: "{{ base_url }}/{{ arch }}/dependencies/rhcos/{{ maj_ver }}/{{ rhcos_version }}/rhcos-{{ rhcos_version }}-{{ arch }}-installer-initramfs.{{ arch }}.img"
coreos_installer_image: "{{ base_url }}/{{ arch }}/dependencies/rhcos/{{ maj_ver }}/{{ rhcos_version }}/rhcos-{{ rhcos_version }}-{{ arch }}-metal.{{ arch }}.raw.gz"
